"""A-001 — the general plan notes, on their own sheet.

   They were on A-101 and A-102 when the set was 22 x 34 portrait: 17.7 inches of a
   32.5-inch sheet. On a 16.5-inch drawing area they no longer fit beside a plan, so
   they moved here and the plan sheets carry a cross-reference. That is also what let
   the plans stay at 1/4" = 1'-0" rather than dropping a scale step.

   Set in TWO COLUMNS. The lines are lifted verbatim from the sheets they replaced,
   so the line COUNT is fixed and only the setting can give."""
from arkitect.lib.units import IN, fmt, inches, inches16
from arkitect.lib.model.dimensions import wc_clearances
from src.finishes import BOARD
from src import clearances as CL
from arkitect.codes import clearances as code_clearances
from src.grading import STOOP_STEP
from arkitect.lib.draw.kit import c
from src import levels
from arkitect.codes.ohio.rco import fire_separation as rco_fsd

from src.building1 import LINE_LOCAL, BAY, DR_CLR, DR_CLR_NEAR, DR_END_SIDE, GL_MIN, GL_OPEN_TEXT, GL_U2, U23_BAYS, U23_HEATER_BAY, U3_LAND_SOFFIT, U3_STAIR, U3_STOOP_HI, WD_SIDE
from src.building2 import GL_U45, MECH_DEPTH, MECH_RUN, U5_LAND_D, U5_LAND_LEN, U5_LAND_SOFFIT, U5_RUN, U5_STAIR_CLR, U5_STAIR_W
from src.mirror import BED_SIDE, LIVE_SIDE
from src.openings import WIN_GEOM, WIN_HEAD, WIN_W
from src.building1 import SX
from arkitect.lib.draw.text import textsheet
from src.fireblocking import FB




# ============================= A-001 PLAN NOTES =============================
# The notes are not a document that happens to quote the drawings — they are built
# from the same values the drawings are, which is why this list lives beside the
# sheet that prints it and not in a data file. Forty-odd derived figures appear in
# it: the glazing percentages, the stair run, the terminations. Mechanical, electrical
# and structural detail is not repeated here: the note points to its home sheet.
# General plan notes — drawn on A-001, referenced from every plan sheet.

def _wc_side():
    """The clearance note 11a quotes: the smaller of the two the Building 1 plans
       dimension at the pan.

       Not a number typed in the note. The citation and both minimums beside it come
       from src/clearances.py and this comes from wc_clearances(), which is the same
       measurement A-101 and A-102 draw -- so the note, the dimension on the sheet and
       the check that passes or fails the build are three readings of one figure. RCO
       307.1 used to live only in prose, in a symbol docstring that said it was checked
       in build.py when nothing was."""
    return min(min(m['cl']-m['lo'], m['hi']-m['cl'])
               for lab, r, po, fu in CL.project_plans() if lab.startswith('BUILDING 1')
               for m in wc_clearances(r, po, fu, BOARD))


PLAN_NOTES = [
        "1.  DIMENSIONS TO FACE OF STUD. VERIFY ALL DIMENSIONS IN THE FIELD. DO NOT SCALE.",
        "1a. INTERIOR DIMENSION STRINGS ARE CLEAR DIMENSIONS, FACE OF STUD TO FACE OF STUD; PARTITION THICKNESS IS NOT INCLUDED IN THEM.",
        "     INTERIOR PARTITIONS ARE TYPE W2 EXCEPT WHERE TAGGED W3 ON THE PLANS.",
        "1b. FLOOR FRAMING, HEADERS, RIMS AND THE UNIT 1 STAIR WELL ARE ON S-102; THE STRIPS AND FOOTINGS UNDER THE BEARING WALLS ARE ON S-101.",
        "2.  EXTERIOR WALLS TYPE W1; USE RATED TYPE W1R WHERE SUPPORTING TYPE F1. INTERIOR PARTITIONS TYPE W2. UNIT SEPARATION WALLS TYPE W3.",
        "     GROUPING SEPARATION TYPE W4. SUPPORTING CONSTRUCTION PER RCO 302.3.1. SEE A-601.",
        "     UNIT 1'S INTERIOR BATH WET WALL IS W6 (2x6).",
        "2a. PENETRATIONS OF W1R SHALL BE PROTECTED PER RCO 302.4 WITH A LISTED THROUGH-PENETRATION SYSTEM OR ANNULAR-SPACE FILL PER THE",
        "     ASSEMBLY LISTING. NO DAMPER IN THE DRYER DUCT.",
        "3.  KITCHENS ARE OPEN TO THE LIVING / DINING SPACE. NO PARTITION BETWEEN THEM. HALLS ARE OPEN — CASED OPENINGS, NO DOORS.",
        "3a. HALLS SHALL HAVE AT LEAST 36\" CLEAR BETWEEN FINISHED FACES. RCO 311.6.",
        f"3b. HEIGHTS: FINISHED FLOORS L1 +{fmt(levels.FF1)}, L2 +{fmt(levels.FF2)}; {inches(levels.FLOOR_RISE)} FINISHED FLOOR TO FINISHED FLOOR. ALLOW {inches(levels.FLOOR_FINISH)} FLOOR FINISH AT BOTH LEVELS.",
        f"     L1 TOP BEARING PLATES: F2 / UNIT 1 +{fmt(levels.F2_PLATE)}; F1 / UNITS 2 AND 4 +{fmt(levels.F1_PLATE)}.",
        "     FINISHED CEILINGS AND THE ASSEMBLY DEPTHS UNDER THEM: A-301 HEIGHT SCHEDULE AND A-601. MINIMUMS: G-001 NOTE 7.",
        "4.  NO PIPING, DUCT OR WIRING SHALL PENETRATE ANY MEMBRANE OF W4A OR W4B. SERVICES RUN IN THE TYPE W5 FURRED CHASE ON THE UNIT SIDE.",
        f"4a. THE UNIT 2 AND UNIT 4 CEILINGS ARE THE F1 MEMBRANE, {levels.F1_LISTING}, A-601. PROTECT EVERY PENETRATION OF IT PER RCO 302.4:",
        "     LUMINAIRES LISTED AND LABELED FOR THE RATED CEILING, OR PROTECTED WITH LISTED MATERIALS TESTED FOR FIRE-RESISTANCE-RATED ASSEMBLIES,",
        "     INSTALLED PER THAT LISTING, 302.4.2 EXCEPTION 4. ELECTRICAL BOXES LISTED AND TESTED FOR USE IN FIRE-RESISTANCE-RATED ASSEMBLIES, INSTALLED PER",
        "     THEIR LISTING, 302.4.2 EXCEPTION 2, OR PROTECTED BY A PENETRATION FIRESTOP SYSTEM. BATH EXHAUST FANS WITH A CEILING RADIATION DAMPER, THE PAIR",
        "     LISTED FOR A 1-HOUR WOOD-JOIST FLOOR-CEILING. PIPES AND DUCTS: A FIRESTOP SYSTEM TO ASTM E814 OR UL 1479, F RATING 1 HOUR, 302.4.1.2.",
        "4b. W4 IS TWO 1-HOUR WALLS, W4A AND W4B, UL U305, 9-1/2\" FINISHED, CONTINUOUS FROM FOUNDATION TO ROOF SHEATHING, RCO 302.2.",
        "     ASSEMBLY, THE FRT ROOF SHEATHING 4'-0\" EACH SIDE AND NO ROOF OPENING IN THAT BAND, RCO 302.2.4: A-601.",
        "4c. FIREBLOCKING PER RCO 302.11: EACH W4 STUD CAVITY AND BOTH W5 CHASES AT EVERY FLOOR AND CEILING LINE, THE UNIT 1 STAIR STRINGERS AT THE TOP",
        f"     AND BOTTOM OF THE RUN, SOFFITS AND DROPPED CEILINGS, AND EVERY PIPE, VENT, CABLE AND WIRE THROUGH A PLATE. SEE A-601 {FB['W4']} TO {FB['DRAFTSTOP']}.",
        "5.  EVERY SLEEPING ROOM IS PROVIDED WITH AN EGRESS WINDOW, TYPE W-A.",
        f"     W-A IS {fmt(WIN_W['A'])} x {fmt(WIN_GEOM['A'][1])}: SILLS {fmt(WIN_GEOM['A'][0])} ABOVE FINISHED FLOOR, HEADS {fmt(WIN_HEAD['A'])}. UNIT 1 KITCHEN USES W-B,"
        f" {fmt(WIN_W['B'])} x {fmt(WIN_GEOM['B'][1])}; W-C RETAINS ITS {fmt(WIN_W['C'])} WIDTH. SEE SCHEDULE, A-602.",
        "     EACH UNIT 4 BEDROOM'S EMERGENCY ESCAPE OPENING, RCO 310.1, IS ITS W-A ON THE SAGE OR ADJACENT-PARCEL WALL, CLEAR OF THE PARKING PAD.",
        f"5a. GLAZING, RCO 303.1 — 8 PERCENT OF FLOOR AREA MINIMUM, MET IN EVERY HABITABLE ROOM. UNITS 2 AND 3: {int(GL_U2['br1'])} PERCENT IN BEDROOM 1,",
        f"     {int(GL_U2['br2'])} PERCENT IN BEDROOM 2, AND {GL_OPEN_TEXT}.",
        f"     UNITS 4 AND 5: {int(GL_U45['br1'])} PERCENT IN BEDROOM 1, {int(GL_U45['br2'])} PERCENT IN BEDROOM 2 AND {int(GL_U45['open'])} PERCENT IN THE OPEN LIVING, DINING AND KITCHEN SPACE.",
        f"     OPENABLE AREA IS {int(GL_MIN/2.0)} PERCENT AND OVER AGAINST THE 4 PERCENT MINIMUM. NO WINDOW STANDS UNDER A STAIR FLIGHT OR A LANDING DECK; ADD NONE THERE.",
        "     BATHROOMS ARE GOVERNED BY RCO 303.3. THE UNITS 1, 2 AND 3 BATHS HAVE NO EXTERIOR WINDOW AND TAKE ITS EXCEPTION, ARTIFICIAL LIGHT AND",
        "     MECHANICAL VENTILATION EXHAUSTED OUTDOORS; THE UNITS 4 AND 5 BATHS HAVE A W-B OVER THE TUB AND ARE ALSO MECHANICALLY EXHAUSTED. NOTE 11.",
        f"5b. RCO 312.2 REQUIRES NO WINDOW FALL PROTECTION. W-A'S SILL IS {fmt(WIN_GEOM['A'][0])}. A FALL PREVENTION DEVICE OR WINDOW GUARD, WHERE PROVIDED, SHALL COMPLY",
        "     WITH ASTM F2090, 312.2.1. IF A SELECTED PRODUCT SETS ITS SILL LOWER, OR A ROUGH OPENING IS DROPPED IN THE FIELD, FIT AN OPENING LIMITING DEVICE",
        "     AT EVERY LEVEL 2 W-A PER 312.2.2, RELEASING FOR ESCAPE WITHOUT KEYS, TOOLS OR SPECIAL KNOWLEDGE, 310.1.1, AND KEEPING THE A-602 MINIMUMS.",
        "6.  SMOKE AND CARBON MONOXIDE ALARMS: G-001 NOTES 9 AND 10; LOCATIONS ON E-101 AND E-102.",
        "7.  EACH DWELLING UNIT IS ENTERED DIRECTLY FROM THE EXTERIOR. NO EXIT IS SHARED BETWEEN UNITS.",
        "8.  MECHANICAL CLOSET IN EACH UNIT HOUSES THE WATER HEATER AND THE STACKED LAUNDRY, ENTERED FROM A HALL OR OPEN LIVING SPACE —",
        "     NEVER THROUGH A BATHROOM. EQUIPMENT: P-601 NOTES 6 AND 7; M-101.",
        f"8a. IN UNITS 2 AND 3 THE MECHANICAL CLOSET STANDS ON THE REAR WALL. ITS {BED_SIDE}-END SIDE PARTITION IS THE BEDROOM 2 CLOSET",
        "     WALL, NOT A SLEEPING-ROOM WALL. INSULATE THAT PARTITION FULL DEPTH WITH MINERAL WOOL.",
        "8b. UNIT 1 MECHANICAL ROOM IS ON LEVEL 1, BESIDE THE SAGE STAIR: 3'-7\" x 9'-5-1/2\" TO STUD FACES, PLUS THE LAUNDRY NOOK.",
        "     THE 2'-8\" LOUVERED DOOR SWINGS OUT INTO THE OPEN LIVING SPACE. PANEL IS ON THE STAIR WALL; THE HEATER STANDS ON THE",
        "     OPPOSITE WALL, PAST THE END OF THE PANEL'S WORKING SPACE, ITS OWN WORKING SPACE ON THE CONTROL SIDE, ALONG THE ROOM.",
        "     THE 27\" x 32\" STACKED W/D SITS AGAINST SAGE UNDER THE FULL-HEIGHT UPPER LANDING, LOADED FROM THE MECHANICAL ROOM.",
        "     KEEP THE WORKING SPACES DRAWN ON A-101 AND THE LAUNDRY LOADING AREA CLEAR; E-101 NOTE 7, M-101 NOTE 8.",
        "     PROVIDE AN UNDER-STAIR STORAGE CLOSET WITH ITS OWN 1'-10\" DOOR AND 1/2\" GYPSUM PROTECTION TO THE UNDERSIDE.",
        "9.  EVERY KITCHEN HAS AT LEAST ONE EXTERIOR WINDOW.",
        "9a. THE PLUMBING FIXTURES, KITCHEN CABINETS AND APPLIANCES, AND THE LAUNDRY AND WATER-HEATER BAYS SHOWN ON THE FLOOR PLANS ARE PART OF",
        "     THE WORK. BEDS (QUEEN 5'-0\" x 6'-8\", FULL 4'-6\" x 6'-3\") ARE DRAWN FOR SPACE PLANNING ONLY; BEDS AND LOOSE FURNITURE ARE NOT IN THE CONTRACT.",
        "10. NO COMBUSTION AIR OPENINGS ARE REQUIRED AT ANY MECHANICAL CLOSET. THIS PROJECT HAS NO FUEL-FIRED APPLIANCE OF ANY KIND AND",
        "     NO FUEL GAS IS SUPPLIED TO THE SITE: WATER HEATING, SPACE HEATING, COOKING AND DRYING ARE ALL ELECTRIC. THE LOUVERED DOOR PAIR",
        "     TYPES D-4 AND D-4A ARE FOR DRYER MAKE-UP AIR ONLY, AND SHALL PROVIDE NOT LESS THAN 100 SQ IN OF FREE AREA, OR THE DRYER MAKER'S LARGER OPENING, RCO M1502.1. UNIT 1 TAKES D-7.",
        "11. NO BATHROOM IN UNITS 1, 2 OR 3 HAS AN EXTERIOR WINDOW; THE UNITS 4 AND 5 BATH HAS A W-B OVER THE TUB, TEMPERED, RCO 308.4.5.",
        "     EVERY BATHROOM IS MECHANICALLY EXHAUSTED OUTDOORS, RCO 303.3, AND ONE BATH FAN PER UNIT RUNS CONTINUOUSLY FOR WHOLE-HOUSE",
        "     VENTILATION, RCO 303.4. RATES, FAN LISTINGS, ROUTES AND CAPS: M-101 NOTES 4 AND 5 AND THE VENTILATION SCHEDULE.",
        f"11a.WATER CLOSET CLEARANCE PER {code_clearances.WC_SIDE.citation}: THE PAN IN UNITS 2 AND 3 IS CENTERED IN THE CLEAR BAND BETWEEN TUB AND VANITY, {fmt(_wc_side())} TO EACH,",
        f"     AGAINST A {inches(code_clearances.WC_SIDE.minimum)} MINIMUM, AND 2'-8\" CLEAR IN FRONT AGAINST A {inches(code_clearances.WC_FRONT.minimum)} MINIMUM. DIMENSIONED ON A-101 AND A-102.",
        "12. UNIT 1: BEDROOM 1 CLOSET IS BEHIND BATH 1; BEDROOM 2 REACH-IN IS FLUSH WITH SAGE AT THE HALL CORNER; BEDROOMS 3 AND 4 HAVE",
        "     SEPARATE CLOSETS IN THE END OF THE HALL BAND. LINEN CLOSET IS BEHIND BATH 2. RODS, SHELVES AND DOORS AS DRAWN.",
        "12a.UNITS 2 AND 3: EACH BEDROOM HAS A 2'-0\" x 6'-6\" REACH-IN. UNITS 4 AND 5 RETAIN THEIR A-103 REACH-INS.",
        "     PROVIDE BUILT-IN CLOSETS IN EVERY BEDROOM. KEEP DOOR SWINGS AND EGRESS WINDOWS CLEAR.",
        "13. UNIT 1 HAS A STRAIGHT STAIR ON THE SAGE WALL, ASCENDING TOWARD THE COMMON WALL: 15 RISERS AT 8\" = 120\" FLOOR TO FLOOR.",
        f"     14 TREADS AT 9-1/4\" GIVE A 10'-9-1/2\" RUN; 1\" NOSINGS / CLOSED RISERS. WIDTH {fmt(SX)} FRAMED, {fmt(SX-IN(1))} FINISHED; 36\" CLEAR LANDINGS.",
        "     PROVIDE 34-38\" HANDRAIL AND 6'-8\" MINIMUM HEADROOM. UPPER WELL STARTS AT 124-1/2\" FROM THE FRONT INTERIOR STUD FACE.",
        "     FIRST RISER IS 111-3/4\" FROM FRONT INTERIOR STUD FACE. HEADROOM PER A-301, 84\" PROJECT MINIMUM; NO DROPPED HEADER, TRIM OR",
        "     SERVICES IN IT.",
        "     L2 HALL-SIDE WELL EDGE: 36\" HIGH GUARD ABOVE FINISHED FLOOR; OPENINGS SHALL NOT PASS A 4\" SPHERE. RCO 312.1.2 / 312.1.3.",
        "     GUARD POSTS THROUGH-BOLTED TO THE HEADER WITH BLOCKING, NOT TO THE SUBFLOOR ALONE. WELL HEADER, TRIMMERS AND F2: S-102.",
        f"13a.UNIT 3'S STRAIGHT EXTERIOR STAIR RUNS ALONG THE {LIVE_SIDE} SIDE AND DESCENDS TOWARD THE REAR TO A 6\" CONCRETE STOOP BEYOND THE REAR WALL,",
        f"     TOP {inches(U3_STAIR.stoop_above_grade)} ABOVE FINISHED GRADE, ONE {inches(STOOP_STEP)} STEP DOWN TO GRADE. STOOP TO LEVEL 2 IS {fmt(U3_STAIR.rise)}: {U3_STAIR.risers} EQUAL RISERS AT {inches16(U3_STAIR.riser)}, {U3_STAIR.treads} TREADS AT {inches(U3_STAIR.tread)}, RUN {fmt(U3_STAIR.run)}.",
        "     THE FLIGHT AND BOTH LANDINGS ARE 3'-6\" OVERALL WITH 3'-0\" MINIMUM CLEAR; THE TOP LANDING IS 3'-6\" SQUARE, OVER THE UNIT 2 ENTRY DOOR,",
        f"     SOFFIT ABOUT {fmt(U3_LAND_SOFFIT)} ABOVE FINISHED GRADE. THE STOOP STOPS {fmt(LINE_LOCAL-U3_STOOP_HI)} SHORT OF THE RCO 302.1 IMAGINARY LINE, C-101 NOTE 5e; DETAILS A-604.",
        "     PROVIDE 34–38\" CONTINUOUS GRASPABLE HANDRAILS, 36\" GUARDS WITH RCO 312.1 OPENING LIMITS, LIGHTING AT TOP AND BOTTOM, AND A",
        "     CANOPY OVER THE UNIT 3 DOOR AND ENTIRE TOP LANDING. THE DOOR SWINGS INWARD; KEEP THE AREA BELOW THE TOP LANDING CLEAR.",
        "     FIRE SEPARATION DISTANCE AND UNDERSIDE RATING: A-601 AND C-101 NOTE 5e.",
        "     BOTH EXTERIOR STAIRS: PRESSURE-TREATED WOOD, PRESCRIPTIVE TO RCO 311.7 AND 507; BUILD, PITCH, ANCHORAGE AND SHOP DRAWING PER A-604.",
        "13b.UNIT 5'S EXTERIOR STAIR IS THE SAME STAIR TURNED THROUGH NINETY DEGREES: IT RUNS ALONG BUILDING 2'S COURTYARD FACE AND",
        f"     DESCENDS TOWARD SAGE. {U3_STAIR.risers} EQUAL RISERS AT {inches16(U3_STAIR.riser)} AND {U3_STAIR.treads} TREADS AT {inches(U3_STAIR.tread)} FROM THE SAME STOOP TO LEVEL 2, HORIZONTAL",
        f"     RUN {fmt(U5_RUN)}, {fmt(U5_STAIR_W)} OVERALL WITH {fmt(3.0)} MINIMUM CLEAR, AND A {fmt(U5_LAND_LEN)} x {fmt(U5_LAND_D)} TOP LANDING OVER UNIT 4'S DOOR AND ITS COURTYARD",
        f"     W-A, SOFFIT ABOUT +{fmt(U5_LAND_SOFFIT)}. HANDRAILS, GUARDS, LIGHTING, THE CANOPY, THE BUILD, THE SUBMITTAL AND",
        f"     THE TREAD PITCH ARE AS NOTE 13a. THE STAIR STANDS {fmt(U5_STAIR_CLR)} FROM THE RCO 302.1 IMAGINARY LINE, OVER THE {fmt(rco_fsd.PROJ_FREE)} OF RCO TABLE 302.1(1);",
        "     ITS UNDERSIDE IS UNRATED. C-101 NOTE 5e.",
        "14. NO ROOM IS ENTERED THROUGH ANOTHER ROOM. EVERY BEDROOM, BATHROOM, MECHANICAL CLOSET AND STAIR IS REACHED FROM A HALL OR FROM THE OPEN",
        "     ENTRY / LIVING / DINING SPACE. NO CIRCULATION PASSES THROUGH A SLEEPING ROOM. A BEDROOM CLOSET IS ENTERED FROM ITS OWN BEDROOM.",
        f"15. UNITS 2 AND 3 MECHANICAL CLOSETS ARE 5'-3\" x 3'-3-5/8\", 17 SF. REAR WALL, {BED_SIDE} END TO {LIVE_SIDE} END ="
        f" {' + '.join('%s %s BAY'%(fmt(BAY(b)),n) for n,b in U23_BAYS)}.",
        f"     THE STACKED WASHER / DRYER IS IN THE {LIVE_SIDE} CORNER; THE STORAGE WATER HEATER STANDS ON THE FLOOR CENTERED IN THE",
        f"     {fmt(BAY(U23_HEATER_BAY))} {BED_SIDE}-END REAR-WALL BAY; THE PANEL IS FLUSH ON THE {BED_SIDE}-END SIDE WALL. THE HEATER'S WORKING SPACE",
        "     IS BORROWED THROUGH THE OPEN LOUVERED PAIR; KEEP IT CLEAR. WORKING SPACES AS DRAWN, E-101 NOTE 7, M-101 NOTE 8.",
        "15a.UNIT 1: 3'-7\" x 9'-5-1/2\" PLUS THE LAUNDRY NOOK, NOTE 8b.",
        f"15b.UNITS 4 AND 5: {fmt(MECH_DEPTH)} x {fmt(MECH_RUN)}, {round(MECH_DEPTH*MECH_RUN)} SF, IN THE SAGE CORNER OF THE KITCHEN AGAINST THE BEARING WALL, ENTERED THROUGH ITS",
        "     LOUVERED PAIR ON THE LONG FACE; W/D, PANEL AND STORAGE HEATER ALONG THE SAGE WALL AS DRAWN. HEATER WORKING SPACE THROUGH THE",
        "     OPEN PAIR. ADD NOTHING TO THE PANEL'S WORKING SPACE. VERIFY THE SELECTED APPLIANCES AGAINST THE BAYS BEFORE FRAMING.",
        "16. DRYER EXHAUST — EACH MECHANICAL CLOSET VENTS ITS DRYER AND NOTHING ELSE, BY THE ROUTES BELOW. DUCT, LENGTH, SLOPE AND CAPS",
        "     PER M-101 NOTE 6; COORDINATE THE TERMINATIONS WITH THE UNIT 3 STAIR, THE METER BANKS AND THE OUTDOOR UNITS, C-101.",
        f"16a.UNITS 2 AND 3: FROM THE {WD_SIDE}-END STACKED DRYER, RISE AND RUN HIGH ALONG THE ROOM SIDE OF THE REAR WALL TO THE FAR {DR_END_SIDE} END,",
        f"     ABOUT 10 FT DEVELOPED, NO SOFFIT, NOT THROUGH THE BEDROOM CLOSETS; TERMINATE HIGH THROUGH THE REAR WALL. THE CAP IS {fmt(DR_CLR)} FROM",
        f"     {DR_CLR_NEAR}. COORDINATE THE TWO REAR-WALL PENETRATIONS, THE DRYER DUCT AND THE STACK E VENT, P-601. SEE A-202.",
        "16b.UNIT 1: SERVICES ON LEVEL 1. THE DRYER DUCT RUNS DIRECTLY OUT THROUGH THE SAGE WALL TO DR-1, THE ONLY TERMINATION ON THAT WALL;",
        "     COORDINATE WITH THE UPPER LANDING WINDOW. SEE A-201 AND C-101.",
        "16c.UNITS 4 AND 5: THE CLOSET TOUCHES BUILDING 2'S SAGE WALL AND THE DRYER DUCT TERMINATES DIRECTLY THROUGH IT.",
        f"17. KITCHENS IN UNITS 2 AND 3 ARE AN L ON THE SEPARATION AND {LIVE_SIDE} WALLS, OPEN TO THE LIVING SPACE ON TWO SIDES: 11'-5-3/8\"",
        f"     OF COUNTER AND A 2'-7-5/8\" REFRIGERATOR NICHE AT THE BATHROOM END OF THE SEPARATION RUN. THE SINK IS ON THE {LIVE_SIDE}",
        "     WALL, CENTERED UNDER THE WINDOW, WITH THE DISHWASHER IN THE 2'-0\" BESIDE IT ON THE LIVING SIDE. THE RANGE IS ON THE SEPARATION RUN.",
        "     SINK, DISHWASHER, RANGE AND REFRIGERATOR ARE DRAWN ON A-101 AND A-102 AND ARE THE CONTRACT PER NOTE 9a.",
        "17a.BOTH KITCHEN SINKS IN BUILDING 1 SIT UNDER A WINDOW ON AN EXTERIOR WALL, NOT ON THE SEPARATION WET PLANE. UNIT 2'S AND",
        "     UNIT 3'S SHARE A STACK; NEITHER W4 WALL CARRIES A COMMON CHASE.",
        "17b.RANGE HOODS: UNIT 1 DUCTED THROUGH THE ADJACENT-PARCEL WALL; UNITS 2, 3, 4 AND 5 DUCTLESS RECIRCULATING. M-101 NOTE 7.",
        "18. HEATING AND COOLING BY DUCTLESS AIR-SOURCE HEAT PUMP, ONE OUTDOOR UNIT PER DWELLING UNIT WITH WALL-MOUNTED HEADS; NO FURNACE,",
        "     AIR HANDLER OR DUCTWORK. EQUIPMENT SELECTION AND SIZING: M-101 NOTE 1.",
        "19. LINE SETS AND CONDENSATE PER M-101 NOTES 2 AND 3. NO LINE SET, DRAIN OR CONTROL WIRE SHALL CROSS W4 OR THE TYPE F1",
        "     FLOOR-CEILING BETWEEN STACKED UNITS.",
]


def sheet_a001():
    textsheet(c,"A-001","Floor plan general notes",
              "GENERAL PLAN NOTES — APPLY TO A-101, A-102 AND A-103",PLAN_NOTES,cols=2,fill=True)
